xenatronics/home/urls.py
from django.urls import path

from .views import home, about, index, custom_login_page, CustomLoginView, CustomLogoutView, profile_view

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('index/', index, name='index'),
    path('profile/', profile_view, name='profile'),  # Page de profil
    path('login/', CustomLoginView.as_view(), name='login'),  # Login via LoginView
    path('logout/', CustomLogoutView.as_view(next_page='/login/'), name='logout'),  # Logout via LogoutView
    path('custom-login-page/', custom_login_page, name='custom_login_page'),  # Page personnalisée
]

xenatronics/xenatronics/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),  # Inclure les routes de l'application 'home'

]

xenatronics/folios/models.py
from django.db import models

# Create your models here.

xenatronics/home/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    birthday = models.DateField(null=True, blank=True)  # Stocke le timestamp
    first_name = models.CharField(max_length=50, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    postal_code = models.CharField(max_length=10, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    alias=models.CharField(max_length=50, blank=True, null=True)

    def format_birthday(self):
        """Convert timestamp to a datetime object."""
        if self.birthday:
            return datetime.fromtimestamp(self.birthday/1000 ).strftime('%Y-%m-%d')
        return None

    def __str__(self):
        return f"Profile de {self.user.username}"

xenatronics/home/forms.py
from django import forms
from .models import UserProfile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [
            'first_name',  'birthday', 'address',
            'postal_code', 'city', 'country', 'phone',
        ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'input-field p-0.5 focus:outline-none focus: border-b focus:border-blue-500'}),
            'birthday': forms.DateInput(attrs={'type':'date','class': 'input-field p-0.5 focus:outline-none focus: border-b focus:border-blue-500'}),
            'address': forms.Textarea(attrs={'class': 'input-field p-0.5 focus:outline-none focus: border-b focus:border-blue-500','cols':30, 'rows': 1}),
            'postal_code': forms.TextInput(attrs={'class': 'input-field p-0.5 focus:outline-none focus: border-b focus:border-blue-500'}),
            'city': forms.TextInput(attrs={'class': 'input-field p-0.5 focus:outline-none focus: border-b focus:border-blue-500'}),
            'country': forms.TextInput(attrs={'class': 'input-field p-0.5 focus:outline-none focus: border-b focus:border-blue-500'}),
            'phone': forms.TextInput(attrs={'class': 'input-field p-0.5 focus:outline-none focus: border-b focus:border-blue-500'}),
        }

xenatronics/folios/views.py
from django.shortcuts import render

# Create your views here.

xenatronics/home/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .forms import ProfileForm


def home(request):
    return render(request, 'home/home.html')

def custom_login_page(request):  # Renommée pour éviter le conflit
    return render(request, 'home/login.html')

def index(request):
    return render(request, 'home/index.html')

def about(request):
    return render(request, 'home/about.html')



@login_required
def profile_view(request):
    profile = request.user.profile  # Accéder au profil lié
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        date_str = request.POST.get('birthday')
        if date_str:
            #date_obj = datetime.strptime(date_str, "%Y-%m-%d")
            #profile.birthday = int(date_obj.timestamp() * 1000)
            #form['birthday'].value = str(date_obj)
            print(form['birthday'].value())

        if form.is_valid():
            form.save()
            messages.success(request, "Vos informations ont été mises à jour avec succès.")
            return redirect('home:profile')
        else:
            print(form.errors)
            messages.error(request, "Une erreur est survenue. Veuillez vérifier les champs.")
    else:
        form = ProfileForm(instance=profile)

    return render(request, 'home/profile.html', {
            'user': request.user,
            'profile': form
        })


class CustomLoginView(LoginView):
    template_name = 'home/login.html'  # Chemin relatif au répertoire templates
    #redirect_authenticated_user = True

    def get_success_url(self):
        return '/profile/'  # Redirige vers la page de profil après connexion



class CustomLogoutView(LogoutView):
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

xenatronics/home/templates/home/home.html
{% extends 'base.html' %}

{% block title %}Accueil{% endblock %}

{% block content %}
<div class="bg-white p-6 rounded-lg shadow-md">
    <h1 class="text-2xl font-bold">Bienvenue</h1>
    <p class="text-gray-500 mt-2">Ceci est une page dynamique construite avec Django et TailwindCSS.</p>
</div>
{% endblock %}

xenatronics/home/templates/home/login.html
{% extends 'base.html' %}
{% load form_filters %}

{% block content %}
<div class="flex justify-center items-center min-h-screen bg-gray-100">
    <div class="max-w-md w-full bg-white p-8 rounded-lg shadow-lg">
        <h1 class="text-2xl font-bold mb-6 text-center text-gray-800">Connexion</h1>
        <form method="post" class="space-y-6">
            {% csrf_token %}
            <div>
                <label for="{{ form.username.id_for_label }}" class="block text-sm font-medium text-gray-700">
                    Nom d'utilisateur
                </label>
                {{ form.username|add_class:"block w-full mt-1 p-2 border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200" }}
            </div>
            <div>
                <label for="{{ form.password.id_for_label }}" class="block text-sm font-medium text-gray-700">
                    Mot de passe
                </label>
                {{ form.password|add_class:"block w-full mt-1 p-2 border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200" }}
            </div>
            <button type="submit" class="w-full bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600">
                Se connecter
            </button>
        </form>
    </div>
</div>
{% endblock %}

xenatronics/home/templates/home/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="flex justify-center items-center h-screen bg-gray-100">

    <div class="max-w-4xl w-full bg-white p-8 rounded-xl shadow-lg">
     {% include 'common/messages.html' %}


        <!-- Titre principal -->
        <div class="text-center mb-6">
            <h1 class="text-4xl font-semibold text-gray-800">
                <i class="fas fa-user-circle text-blue-500"></i> Bienvenue, {{ user.username|default:"Sans nom" }}!
            </h1>
            <p class="text-gray-500 text-lg mt-2">Découvrez vos informations et gérez votre compte ici.</p>
        </div>

        <!-- Contenu -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <!-- Carte Informations générales -->
            <div class="bg-gray-50 p-5 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300 flex flex-col">
                <h2 class="text-2xl font-medium text-gray-700 mb-6">
                    <i class="fas fa-info-circle text-green-500"></i> Informations générales
                </h2>
                <div class="grid grid-cols-1 gap-3 flex-grow">
                    <div class="flex items-center text-gray-700">
                        <i class="fas fa-user text-gray-500 mr-3"></i>
                        <span class="font-medium pr-1">Nom d'utilisateur :</span> {{ user.username|default:"Sans nom" }}
                    </div>
                    <div class="flex items-center text-gray-700">
                        <i class="fas fa-envelope text-gray-500 mr-3"></i>
                        <span class="font-medium pr-1">Adresse e-mail :</span> {{ user.email }}
                    </div>
                    <div class="flex items-center text-gray-700">
                        <i class="fas fa-calendar-alt text-gray-500 mr-3"></i>
                        <span class="font-medium pr-1">Date d'inscription :</span> {{ user.date_joined|date:"d M Y" }}
                    </div>
                    <div class="flex items-center">
                        <i class="fas fa-user-tag text-gray-500 mr-3"></i>
                        <span class="font-medium text-gray-700 pr-1">Statut :</span>
                        <span class="ml-2 px-3 py-1 text-sm text-white bg-green-500 rounded-full">
                            {{ profile.status|default:"Utilisateur" }}
                        </span>
                    </div>
                </div>
                <div>&nbsp;</div>
                <div>&nbsp;</div>
                <div>&nbsp;</div>
                <div>&nbsp;</div>
                <div>&nbsp;</div>
                <form method="post" action="{% url 'home:logout' %}" class="mt-auto">
                    {% csrf_token %}
                    <button type="submit"
                            class="mt-4 px-6 py-3 text-white bg-red-500 rounded-lg shadow hover:bg-red-600 transition-colors duration-300">
                        <i class="fas fa-sign-out-alt"></i> Se déconnecter
                    </button>
                </form>
            </div>

            <!-- Carte Informations personnelles -->

            <form method="post" action="{% url 'home:profile' %}">
                {% csrf_token %}
                {{ profile_form.as_p }}

                <div class="bg-gray-50 p-6 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
                    <h2 class="text-2xl font-medium text-gray-700 mb-6">
                        <i class="fas fa-user-edit text-blue-500"></i> Informations personnelles
                    </h2>

                    <div class="grid grid-cols-1 gap-4">
                        <div class="flex items-center text-gray-700">
                            <i class="fas fa-id-card text-gray-500 mr-3"></i>
                            <span class="font-medium pr-1">Prénom :</span> {{ profile.first_name|default:"Non renseigné" }}
                        </div>
                        <div class="flex items-center text-gray-700">
                            <i class="fas fa-birthday-cake text-gray-500 mr-3"></i>
                            <span class="font-medium pr-1">Date de naissance :</span>{{ profile.birthday|default:"Non renseigné" }}
                        </div>
                        <div class="flex items-center text-gray-700">
                            <i class="fas fa-phone-alt text-gray-500 mr-3"></i>
                            <span class="font-medium pr-1">Téléphone :</span> {{ profile.phone|default:"Non renseigné" }}
                        </div>
                        <div class="flex items-center text-gray-700">
                            <i class="fas fa-map-marker-alt text-gray-500 mr-3"></i>
                            <span class="font-medium pr-1">Adresse :</span> {{ profile.address|default:"Non renseignée" }}
                        </div>
                        <div class="flex items-center text-gray-700">
                            <i class="fas fa-mail-bulk text-gray-500 mr-3"></i>
                            <span class="font-medium pr-1">Code Postal :</span> {{ profile.postal_code|default:"Non renseigné" }}
                        </div>
                        <div class="flex items-center text-gray-700">
                            <i class="fas fa-city text-gray-500 mr-3"></i>
                            <span class="font-medium pr-1">Ville :</span> {{ profile.city|default:"Non renseignée" }}
                        </div>
                        <div class="flex items-center text-gray-700">
                            <i class="fas fa-globe text-gray-500 mr-3"></i>
                            <span class="font-medium pr-1">Pays :</span> {{ profile.country|default:"Non renseigné" }}
                        </div>
                    </div>

                <button type="submit"
                        class="mt-12 px-6 py-3 bg-blue-500 text-white rounded-lg shadow hover:bg-blue-600 transition duration-300">
                    <i class="fas fa-save"></i> Enregistrer les modifications
                </button>
                </div>


            </form>
        </div>


    </div>
</div>
{% endblock %}


{% block javascript %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const messages = document.querySelectorAll('#message-container > div');

        messages.forEach((message, index) => {
            // Délai de disparition automatique
            setTimeout(() => {
                if (message) {
                    message.classList.add('opacity-0'); // Ajoute un effet de disparition
                    setTimeout(() => message.remove(), 500); // Supprime après l'animation
                }
            }, (index + 1) * 3000); // Décalage de 3 secondes entre les messages
        });
    });
</script>
{% endblock %}

xenatronics/templates/common/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mon Site{% endblock %}</title>
<!--    <link href="{% static 'css/output.css' %}" rel="stylesheet">-->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@latest/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

</head>
<body class="bg-gray-100">
<div class="flex flex-container min-h-screen">
<!-- Navbar -->
    {% include 'common/navbar.html' %}
    <!-- Main Content -->
    <div class="container mx-auto mt-0">
        {% block content %}
        {% endblock %}
    </div>
</div>
{% block javascript %}
{% endblock %}
</body>
</html>

xenatronics/templates/common/messages.html
{% if messages %}
        <div id="message-container" class="fixed top-2 right-4 z-50 space-y-2">
        {% for message in messages %}
            <div class="relative p-4 rounded-lg shadow-md text-white transition-opacity duration-300 opacity-100
            {% if message.tags == 'success' %}
                bg-gradient-to-b from-green-400 via-green-500 to-green-600
            {% elif message.tags == 'error' %}
                bg-gradient-to-b from-red-400 via-red-500 to-red-600
            {% else %}
                bg-gradient-to-b from-gray-400 via-gray-500 to-gray-600
            {% endif %}
            ">
            <button class="absolute top-1 right-1 text-white hover:text-gray-200" onclick="this.parentElement.remove()">
                &times;
            </button>
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

xenatronics/templates/common/navbar.html
{% load static %}
<nav class="h-screen bg-gradient-to-b from-gray-900 to-gray-800 text-white w-64 shadow-lg">
    <ul class="mt-6 space-y-2">
        <!-- Accueil -->
        <li class="group">
            <a href="{% url 'home:home' %}" class="flex items-center p-4 hover:bg-gray-700 transition duration-200">
                <i class="fas fa-home w-6 group-hover:scale-110 transition-transform duration-200"></i>
                <span class="ml-4 text-gray-200 group-hover:text-blue-400 font-medium">Accueil</span>
            </a>
        </li>

        {% if user.is_authenticated %}
        <!-- Profil -->
        <li class="group">
            <a href="{% url 'home:profile' %}" class="flex items-center p-4 hover:bg-gray-700 transition duration-200">
                <i class="fas fa-user  w-5 group-hover:scale-110 transition-transform duration-200"></i>
                <span class="ml-4 text-gray-200 group-hover:text-purple-400 font-medium">Profil</span>
            </a>
        </li>

        <!-- Projets -->
        <li class="group">
            <a href="https://github.com/mon-utilisateur" target="_blank"
               class="flex items-center p-4 hover:bg-gray-700 transition duration-200">
                <i class="fab fa-github w-5 group-hover:scale-110 transition-transform duration-200"></i>
                <span class="ml-4 text-gray-200 group-hover:text-yellow-400 font-medium">Projets</span>
            </a>
        </li>

        <!-- Déconnexion -->
        <li class="group">
            <form method="post" action="{% url 'home:logout' %}">
                {% csrf_token %}
                <div class="flex items-center p-4 hover:bg-gray-700 transition duration-200">
                    <i class="fas fa-sign-out-alt w-5 group-hover:scale-110 transition-transform duration-200"></i>
                    <button type="submit"
                            class="ml-4 text-gray-200 group-hover:text-red-400 font-medium transition-colors duration-200">
                        Se déconnecter
                    </button>
                </div>
            </form>
        </li>
        {% else %}
        <!-- Connexion -->
        <li class="group">
            <a href="{% url 'home:login' %}" class="flex items-center p-4 hover:bg-gray-700 transition duration-200">
                <i class="fas fa-sign-in-alt w-5 group-hover:scale-110 transition-transform duration-200"></i>
                <span class="ml-4 text-gray-200 group-hover:text-green-400 font-medium">Connexion</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>